# Generated by Django 5.2.5 on 2025-10-08 18:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('buyer_id', models.BigIntegerField()),
                ('seller_id', models.BigIntegerField()),
                ('listing_id', models.BigIntegerField()),
                ('listing_title', models.CharField(blank=True, default='', max_length=255)),
                ('listing_price_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('listing_price_currency', models.CharField(blank=True, default='', max_length=3)),
                ('listing_thumbnail_url', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('closed', 'Closed')], default='active', max_length=16)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_preview', models.CharField(blank=True, default='', max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['buyer_id'], name='chat_chatth_buyer_i_ffa944_idx'), models.Index(fields=['seller_id'], name='chat_chatth_seller__9aa90f_idx'), models.Index(fields=['listing_id'], name='chat_chatth_listing_fea8b4_idx'), models.Index(fields=['status', 'updated_at'], name='chat_chatth_status_429830_idx')],
                'constraints': [models.UniqueConstraint(fields=('buyer_id', 'listing_id'), name='uniq_chat_thread_buyer_listing')],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_id', models.BigIntegerField()),
                ('sender_display_name', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('client_message_id', models.CharField(blank=True, default='', max_length=64)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatthread')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['thread', 'created_at'], name='chat_chatme_thread__b4c881_idx'), models.Index(fields=['sender_id'], name='chat_chatme_sender__3a9411_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatThreadParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('role', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller')], max_length=16)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('is_archived', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('unread_count', models.PositiveIntegerField(default=0)),
                ('last_read_message_id', models.UUIDField(blank=True, null=True)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='chat.chatthread')),
            ],
            options={
                'indexes': [models.Index(fields=['user_id', 'is_deleted'], name='chat_chatth_user_id_7e3f1c_idx'), models.Index(fields=['thread', 'role'], name='chat_chatth_thread__dc32e6_idx')],
                'constraints': [models.UniqueConstraint(fields=('thread', 'user_id'), name='uniq_chat_participant_per_thread')],
            },
        ),
    ]
