# Generated by Django 5.2.5 on 2025-09-02 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savedsearches', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='savedsearch',
            new_name='savedsearch_user_id_56e988_idx',
            old_name='savedsearc_user_id__a4a102_idx',
        ),
    ]
