# Generated by Django 5.2.5 on 2025-09-02 18:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='listing',
            new_name='listings_li_status_c7f971_idx',
            old_name='listings_li_status__b5b46d_idx',
        ),
        migrations.RenameIndex(
            model_name='listingattributevalue',
            new_name='listings_li_listing_722baf_idx',
            old_name='listings_li_listing_5b89a7_idx',
        ),
        migrations.RenameIndex(
            model_name='listingattributevalue',
            new_name='listings_li_attribu_281b35_idx',
            old_name='listings_li_attribu_4c4225_idx',
        ),
        migrations.AlterField(
            model_name='listing',
            name='refreshed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
