# Generated by Django 5.2.5 on 2025-11-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_add_deal_seller_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='listing',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='listing',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
