# Generated by Django 5.2.5 on 2025-11-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_banner_profile_location_profile_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_active_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
