# Generated by Django 5.2.5 on 2025-11-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='otpcode',
            name='purpose',
            field=models.CharField(choices=[('login', 'Login'), ('password_reset', 'Password Reset')], default='login', max_length=20),
        ),
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['email', 'expires_at'], name='accounts_ot_email_89fc22_idx'),
        ),
    ]
