# Generated by Django 5.2.5 on 2025-12-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_telegram_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_e164',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
