# Generated by Django 5.2.5 on 2025-12-07 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_phone_e164'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramChatConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(db_index=True, help_text='Telegram channel/group chat ID')),
                ('chat_type', models.CharField(help_text='Type: channel, supergroup, group', max_length=20)),
                ('chat_title', models.CharField(blank=True, default='', help_text='Channel/group title', max_length=255)),
                ('chat_username', models.CharField(blank=True, default='', help_text='Channel/group username (if public)', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether bot is currently active in chat')),
                ('bot_status', models.CharField(default='administrator', help_text="Bot's current status: administrator, member, left, kicked", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_verified_at', models.DateTimeField(blank=True, help_text='Last time bot status was verified', null=True)),
                ('profile', models.ForeignKey(help_text='User profile that owns this chat configuration', on_delete=django.db.models.deletion.CASCADE, related_name='telegram_chats', to='accounts.profile')),
            ],
            options={
                'db_table': 'telegram_chat_configs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['chat_id', 'is_active'], name='telegram_ch_chat_id_306e49_idx'), models.Index(fields=['profile', 'is_active'], name='telegram_ch_profile_289277_idx'), models.Index(fields=['created_at'], name='telegram_ch_created_3ed8ed_idx')],
                'unique_together': {('profile', 'chat_id')},
            },
        ),
    ]
