# Generated by Django 5.2.5 on 2025-12-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_telegramchatconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramchatconfig',
            name='chat_photo',
            field=models.ImageField(blank=True, help_text='Chat photo/avatar', null=True, upload_to='telegram_chats/'),
        ),
    ]
