# Generated by Django 5.2.5 on 2025-09-02 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='report',
            new_name='moderation__status_2a84ce_idx',
            old_name='moderation_status__b26e87_idx',
        ),
    ]
