# Generated by Django 5.2.5 on 2025-09-02 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_attribute_requirements'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attribute',
            new_name='taxonomy_at_categor_42e3d6_idx',
            old_name='taxonomy_at_categor_6d5ae1_idx',
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='taxonomy_ca_parent__1d5774_idx',
            old_name='taxonomy_ca_parent__e5bfe2_idx',
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='taxonomy_ca_order_d21d6c_idx',
            old_name='taxonomy_ca_order_5ddc7c_idx',
        ),
        migrations.RenameIndex(
            model_name='location',
            new_name='taxonomy_lo_parent__5c7e31_idx',
            old_name='taxonomy_lo_parent__bcb28a_idx',
        ),
    ]
