# Generated by Django 5.2.5 on 2025-10-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0008_add_village_quarter_kinds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='kind',
            field=models.CharField(choices=[('COUNTRY', 'Country'), ('REGION', 'Region'), ('CITY', 'City'), ('DISTRICT', 'District')], max_length=16),
        ),
    ]
